# Generated by Django 5.0.3 on 2024-05-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareMarketplaceApp', '0002_alter_caregiverbiodataprofile_datecreated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carehomeprofile',
            name='dateCreated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
